#!/bin/bash

#Dawid

declare -A PLANSZA

KONIEC=0
ILOSC=0
INPUTBOOLEAN=0
GRACZ=1

function przygotowanie_planszy {
	for((x=0;x<3;x++)) do
		for((y=0;y<3;y++)) do
			PLANSZA[$x,$y]=0
		done
	done
}

function wyswietl_plansze {
	for((x=0;x<3;x++)) do
		for((y=0;y<3;y++)) do
			echo -n ${PLANSZA[$x,$y]}
		done
		echo ''
	done
}

function sprawdz_dane_wejsciowe {
	if [[ $@ -le -1 || $@ -ge 3 ]]; then
		echo 'Podałeś zla wspolrzedna z poza zakresu'
		INPUTBOOLEAN=0
	else
		INPUTBOOLEAN=1
	fi
}

function procesuj_wspolrzedne {
	if [ ${PLANSZA[$@]} = 0 ]; then
		INPUTBOOLEAN=1
		if [ $GRACZ = 1 ]; then
			PLANSZA[$@]=1
			sprawdz_czy_wygrana
			GRACZ=2
		else
			PLANSZA[$@]=2
			sprawdz_czy_wygrana
			GRACZ=1
		fi
	else
		clear
		wyswietl_plansze
		echo 'Wybrane pole jest juz zajete'
		INPUTBOOLEAN=0;
	fi
}

function wprowadz_wspolrzedne {
	while [ $INPUTBOOLEAN = 0 ]; do	
		while [ $INPUTBOOLEAN = 0 ]; do
			echo 'Podaj pierwsza współrzedna(wiersz) od 0 do 2 '
			read x
			sprawdz_dane_wejsciowe $x
		done
		INPUTBOOLEAN=0
		while [ $INPUTBOOLEAN = 0 ]; do
			echo 'Podaj druga współrzedna(kolumna) od 0 do 2'
			read y
			sprawdz_dane_wejsciowe $y
		done
		INPUTBOOLEAN=0
		procesuj_wspolrzedne $x,$y
	done
	INPUTBOOLEAN=0
	let ILOSC=ILOSC+1;
	zapisz_gre
}

function sprawdz_czy_wygrana {
#sprawdzanie wierszy i kolumn
	wyswietl_plansze
		for((x=0;x<3;x++)) do
			if [ ${PLANSZA[$x,0]} = $GRACZ ] && [ ${PLANSZA[$x,0]} = ${PLANSZA[$x,1]} ] && [ ${PLANSZA[$x,0]} = ${PLANSZA[$x,2]} ]; then
				echo 'WYGRANA GRACZA:'$GRACZ
				KONIEC=1;
			elif [ ${PLANSZA[0,$x]} = $GRACZ ] && [ ${PLANSZA[0,$x]} = ${PLANSZA[1,$x]} ] && [ ${PLANSZA[0,$x]} = ${PLANSZA[2,$x]} ]; then
				echo 'WYGRANA GRACZ:' $GRACZ
				KONIEC=1;
			fi
		done
#SKOSY
		if [ ${PLANSZA[1,1]} = $GRACZ ]; then	
			if [ ${PLANSZA[1,1]} = ${PLANSZA[0,0]} ] && [ ${PLANSZA[1,1]} = ${PLANSZA[2,2]} ]; then
				echo 'WYGRANA PO SKOSIE GRACZA:'$GRACZ
				KONIEC=1;	
			elif [ ${PLANSZA[1,1]} = ${PLANSZA[2,0]} ] && [ ${PLANSZA[1,1]} = ${PLANSZA[0,2]} ]; then
				echo 'WYGRANA PO SKOSIE GRACZA:'$GRACZ
				KONIEC=1;
			fi
		fi


}

function gra {
	clear
	echo 'Witaj w grze kółko i krzyżyk'
	sleep 1
	echo 'Gra posiada automatyczny zapis gry co każdą runde'
	sleep 2
	echo 'Jesli przerwiersz rozgrywke bedziesz mogl do niej wrocic'
	sleep 2
	if [ -e ./save/zapisGry.txt ]; then
		wybor='t';
		while [ $wybor != 'y' -a $wybor != 'n' ]; do
			echo 'Wykryto niedokonczona rozgrywke czy chcesz ja dokonczyc? [y/n]'
			read wybor
		done
		if [ $wybor = 'y' ]; then
			echo 'Ladowanie poprzedniej rozgrywki'
			ladowanie_poprzedniej_rozgrywki
			rozpocznij_gre
		else
			echo 'Rozgrywka zostanie nadpisana przez nowa obecna'
			sleep 2
			nowa_gra
		fi
	else
		nowa_gra	
	fi
}

function ladowanie_poprzedniej_rozgrywki {

	ZMIENNA=()
	k=0;
	for i in `cat ./save/zapisGry.txt`
	do
		echo 'cos robie'
		ZMIENNA[$k]=$i
		k=$(($k+1));
	done
	echo ${ZMIENNA[*]}

GRACZ=${ZMIENNA[0]}
ILOSC=${ZMIENNA[1]}
cc=2
for ((x=0;x<3;x++)) do
	for((y=0;y<3;y++)) do
	PLANSZA[$x,$y]=${ZMIENNA[$cc]}
	cc=$(($cc+1))
done
done
}
function nowa_gra {
	przygotuj_katalog_save
	przygotowanie_planszy
#Losowy start gracza
	GRACZ=$((1 + $RANDOM %2))
	rozpocznij_gre
}

function rozpocznij_gre {
	clear
	while [ $KONIEC = 0 ]; do
		clear
		echo 'Kolejka GRACZ:' $GRACZ
		wyswietl_plansze
		if [ $ILOSC -le 8 ]; then
			wprowadz_wspolrzedne
		else
			echo 'REMIS'
			KONIEC=1;
			zapisz_gre
		fi
	done
	echo 'Dziekujemy za gre'

}


function przygotuj_katalog_save {
	if [ ! -d ./save ]; then
		mkdir ./save
	elif [ -e ./save/zapisGry.txt ]; then
		rm ./save/zapisGry.txt
	fi
}

function zapisz_gre {
	if [ $KONIEC = 0 ]; then

	if [ -e ./save/zapisGry.txt ]; then
		rm ./save/zapisGry.txt
	fi
	touch ./save/zapisGry.txt
	echo $GRACZ | tee -a  ./save/zapisGry.txt
	 echo $ILOSC | tee -a  ./save/zapisGry.txt
	
	for ((x=0;x<3;x++)) do
		for ((y=0;y<3;y++)) do
			 echo ${PLANSZA[$x,$y]} | tee -a  ./save/zapisGry.txt
		done
	done
else
	if [ -e ./save/zapisGry.txt ]; then
		rm ./save/zapisGry.txt
	fi
fi
}


gra
