#!/bin/bash

#Dawid

declare -A PLANSZA

KONIEC=0
ILOSC=0
INPUTBOOLEAN=0
GRACZ=1

function przygotowanie_planszy {
	for((x=0;x<3;x++)) do
		for((y=0;y<3;y++)) do
			PLANSZA[$x,$y]=0
		done
	done
}

function wyswietl_plansze {
	clear	
	for((x=0;x<3;x++)) do
		for((y=0;y<3;y++)) do
			echo -n ${PLANSZA[$x,$y]}
		done
		echo ''
	done
}

function sprawdz_dane_wejsciowe {
	if [[ $@ -le -1 || $@ -ge 3 ]]; then
		echo 'Podałeś zla wspolrzedna z poza zakresu'
		INPUTBOOLEAN=0
	else
		INPUTBOOLEAN=1
	fi
}

function procesuj_wspolrzedne {
	if [ ${PLANSZA[$@]} = 0 ]; then
		INPUTBOOLEAN=1
		if [ $GRACZ = 1 ]; then
			PLANSZA[$@]=1
			sprawdz_czy_wygrana
			GRACZ=2
		else
			PLANSZA[$@]=2
			sprawdz_czy_wygrana
			GRACZ=1
		fi
	else
		clear
		wyswietl_plansze
		echo 'Wybrane pole jest juz zajete'
		INPUTBOOLEAN=0;
	fi
}

function wprowadz_wspolrzedne {
	while [ $INPUTBOOLEAN = 0 ]; do	
		while [ $INPUTBOOLEAN = 0 ]; do
			echo 'Podaj pierwsza współrzedna od 0 do 2'
			read x
			sprawdz_dane_wejsciowe $x
		done
		INPUTBOOLEAN=0
		while [ $INPUTBOOLEAN = 0 ]; do
			echo 'Podaj druga współrzedna od 0 do 2'
			read y
			sprawdz_dane_wejsciowe $y
		done
		INPUTBOOLEAN=0
		procesuj_wspolrzedne $x,$y
	done
	INPUTBOOLEAN=0
	let ILOSC=ILOSC+1;
}

function sprawdz_czy_wygrana {
#sprawdzanie wierszy i kolumn
	wyswietl_plansze
		for((x=0;x<3;x++)) do
			if [ ${PLANSZA[$x,0]} = $GRACZ ] && [ ${PLANSZA[$x,0]} = ${PLANSZA[$x,1]} ] && [ ${PLANSZA[$x,0]} = ${PLANSZA[$x,2]} ]; then
				echo 'WYGRANA GRACZA:'$GRACZ
				KONIEC=1;
			elif [ ${PLANSZA[0,$x]} = $GRACZ ] && [ ${PLANSZA[0,$x]} = ${PLANSZA[1,$x]} ] && [ ${PLANSZA[0,$x]} = ${PLANSZA[2,$x]} ]; then
				echo 'WYGRANA GRACZ:' $GRACZ
				KONIEC=1;
			fi
		done
#SKOSY
		if [ ${PLANSZA[1,1]} = $GRACZ ]; then	
			if [ ${PLANSZA[1,1]} = ${PLANSZA[0,0]} ] && [ ${PLANSZA[1,1]} = ${PLANSZA[2,2]} ]; then
				echo 'WYGRANA PO SKOSIE GRACZA:'$GRACZ
				KONIEC=1;	
			elif [ ${PLANSZA[1,1]} = ${PLANSZA[2,0]} ] && [ ${PLANSZA[1,1]} = ${PLANSZA[0,2]} ]; then
				echo 'WYGRANA PO SKOSIE GRACZA:'$GRACZ
				KONIEC=1;
			fi
		fi

}

function gra {
	przygotowanie_planszy
#Losowy start gracza
	GRACZ=$((1 + $RANDOM %2))
	while [ $KONIEC = 0 ]; do
		wyswietl_plansze
		echo 'Kolejka GRACZ:' $GRACZ
		if [ $ILOSC -le 8 ]; then
			wprowadz_wspolrzedne
		else
			echo 'REMIS'
			KONIEC=1;
		fi

	done
	echo 'Dziekujemy za gre'

}

gra
